name: Security Scan
on: [push, pull_request]
jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://docker.io/fluidattacks/skims:latest
        name: skimsStandalone
        with:
          args: skims scan ./config.yml

      - name: Upload Fluid Attacks Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fluid-attacks-results
          path: Fluid-Attacks-Results.csv
